# Generated by Django 4.1.9 on 2023-06-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalquery",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Query",
                "verbose_name_plural": "historical Queries",
            },
        ),
        migrations.AlterModelOptions(
            name="query",
            options={"verbose_name": "Query", "verbose_name_plural": "Queries"},
        ),
        migrations.RenameField(
            model_name="historicalquery",
            old_name="date_BHH_received",
            new_name="date_BMH_received",
        ),
        migrations.RenameField(
            model_name="query",
            old_name="date_BHH_received",
            new_name="date_BMH_received",
        ),
        migrations.AddField(
            model_name="historicalquery",
            name="date_due",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="query",
            name="date_due",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalquery",
            name="affiliations",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="historicalquery",
            name="query_redirected_to",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="query",
            name="affiliations",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="query",
            name="query_redirected_to",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
