# Generated by Django 4.1.9 on 2023-06-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_historicalquery_options_alter_query_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalquery",
            name="bmh_scientific_evaluator_lead",
        ),
        migrations.RemoveField(
            model_name="query",
            name="bmh_scientific_evaluator_lead",
        ),
        migrations.AddField(
            model_name="historicalquery",
            name="food",
            field=models.CharField(
                choices=[
                    ("Poultry", "Poultry"),
                    ("Beef", "Beef"),
                    ("Pork", "Pork"),
                    ("Dairy", "Dairy"),
                    ("Eggs", "Eggs"),
                    ("Grains or baked", "Grains or baked"),
                    ("Ready-to-Eat", "Ready-to-Eat"),
                    ("Canned food", "Canned food"),
                    ("Frozen food", "Frozen food"),
                    ("Fish", "Fish"),
                    ("Seafood", "Seafood"),
                    ("Fruit", "Fruit"),
                    ("Vegetables", "Vegetables"),
                    ("Infant formula", "Infant formula"),
                    ("Not Applicable / Other", "Not Applicable / Other"),
                ],
                default="Not Applicable / Other",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="query",
            name="food",
            field=models.CharField(
                choices=[
                    ("Poultry", "Poultry"),
                    ("Beef", "Beef"),
                    ("Pork", "Pork"),
                    ("Dairy", "Dairy"),
                    ("Eggs", "Eggs"),
                    ("Grains or baked", "Grains or baked"),
                    ("Ready-to-Eat", "Ready-to-Eat"),
                    ("Canned food", "Canned food"),
                    ("Frozen food", "Frozen food"),
                    ("Fish", "Fish"),
                    ("Seafood", "Seafood"),
                    ("Fruit", "Fruit"),
                    ("Vegetables", "Vegetables"),
                    ("Infant formula", "Infant formula"),
                    ("Not Applicable / Other", "Not Applicable / Other"),
                ],
                default="Not Applicable / Other",
                max_length=50,
            ),
        ),
    ]
