# Generated by Django 4.1.9 on 2023-06-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_historicalquery_bmh_scientific_evaluator_lead_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalquery",
            old_name="additiona_information",
            new_name="additional_information",
        ),
        migrations.RenameField(
            model_name="query",
            old_name="additiona_information",
            new_name="additional_information",
        ),
        migrations.AddField(
            model_name="historicalquery",
            name="quarter",
            field=models.CharField(
                choices=[
                    ("Q1", "Q1"),
                    ("Q2", "Q2"),
                    ("Q3", "Q3"),
                    ("Q4", "Q4"),
                    ("Not Applicable / Other", "Not Applicable / Other"),
                ],
                default="Not Applicable / Other",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="query",
            name="quarter",
            field=models.CharField(
                choices=[
                    ("Q1", "Q1"),
                    ("Q2", "Q2"),
                    ("Q3", "Q3"),
                    ("Q4", "Q4"),
                    ("Not Applicable / Other", "Not Applicable / Other"),
                ],
                default="Not Applicable / Other",
                max_length=50,
            ),
        ),
    ]
