# Generated by Django 4.1.9 on 2023-07-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_rename_additiona_information_historicalquery_additional_information_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalquery",
            name="rau",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="query",
            name="rau",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalquery",
            name="section_head",
            field=models.CharField(
                choices=[
                    ("Angela Catford", "Angela Catford"),
                    ("Marie Breton", "Marie Breton"),
                    ("Not Applicable / Other", "Not Applicable / Other"),
                ],
                default="Not Applicable / Other",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="query",
            name="section_head",
            field=models.CharField(
                choices=[
                    ("Angela Catford", "Angela Catford"),
                    ("Marie Breton", "Marie Breton"),
                    ("Not Applicable / Other", "Not Applicable / Other"),
                ],
                default="Not Applicable / Other",
                max_length=500,
            ),
        ),
    ]
